### ISSUE TITLE
Support  inheritance

### ISSUE THREAD

**Issue by andrzejpakula** [omines/datatables-bundle#13] opened 2017-12-30 15:55 UTC
Hey. The bundle promises to be very good. More comfortable to use than stwe. I have a problem. In the case of ORM inheritance, the field option does not read data - the columns are empty. It also does not throw any exception. Am I doing something wrong, is there really no support? I solved this problem in such a way that I process context in a callback render, but it would be nice if support for inheritance would exist. P.S Sorry for my bad english

`
// ...
@ORM\InheritanceType("JOINED")
abstract class Address {
    private $id;
}

// ...
class OrderAddress extends Address {
}

class Order {

@ORM\ManyToOne(targetEntity=OrderAddress::class, cascade={"persist"})
  private $address;
}

// ... in Controller
 ->add('address', TextColumn::class, [
     'field' => 'address.id' // not working
])

`

**Comment by curry684** [comment] 2017-12-30 16:45
Thanks for the kind words, do star the repo so it gets more attention   😄 

I don't think the issue stems from ORM inheritance since Doctrine, to my knowledge, just merges the metadata itself. The field retrieval is allowed to fail itself, it should in that case just fall back to the columns data field or function. We may also just be failing to actually select the field since it's not on the entity itself.

Can you change the definition to this:
```
->add('address', TextColumn::class, [
  'field' => 'address.id' // not working
  'data' => function($value, OrderAddress $address) {
    dump($value, $address);
  }
])
```
And then see in the dump whether the ID just did not get hydrated/selected?

**Comment by curry684** [comment] 2017-12-30 21:03
I have modified the test fixtures to reproduce this issue, yet didn't find any issue. Specifically the fixture controller https://github.com/omines/datatables-bundle/blob/6401cc6926b78f74e22e4c8b205847123519c50f/tests/Fixtures/AppBundle/Controller/PlainController.php should reproduce this issue, but it doesn't. So the issue isn't in inheritance itself for sure.

Does the `id` field have a public getter in your base entity?

**Comment by andrzejpakula** [comment] 2017-12-31 09:48
Hi. This is not really a matter of inheritance. I forgot that I had one more ClientAddress entity that inherited from OrderAddress. There were only ClientAddress objects in the database. I thinked that since ClientAddress inherits from the Order Address, there will be a key. But ORM combines all inheriting tables with a parent, a foreign key in a parent. So I made a call in the Order to Address table and now it works.So I raised unnecessarily false alarm.I have a different question now. I need to render a pair of fields from the table address. But when I set up the address connection with a field, context throws an incomplete object only this one field.

`
     // ...
      ->add('address', TextColumn::class, [
                'field' => 'address.id',
                'orderField' => 'address.city',
                
                'render' => function(string $value, Address $address) use ($addressRepo) {
                 
                // ... dump context throw don't full object 
               ClientAddress {#1134 ▼
                    #name: null
                   #clientAccount: ClientAccount {#460 ▶}
                   -id: 2   
                   -city: null  // i  set field to e.g address.city object has only city etc.
                   -fullName: null
                   -companyName: null
                   -street: null
                   -number: null
                  -postalCode: null
                  -phone: null
                  -email: null
               }

                    return $this->twig->render('account/address_column.html.twig', [
                        'address' => $addressRepo->findOrderAddress($value)
                    ]);
                },
            ])

`
I dealt with it in this way that I created a method in the repository. But she must return ArrayResult.

`

 /**
     * @param int $id
     * @return array
     */
    public function findOrderAddress(int $id): array
    {
        $qb = $this->createQueryBuilder('address');

        $qb
            ->leftJoin(OrderAddress::class, 'order_address', Expr\Join::WITH, 'address.id = order_address.id')
            ->leftJoin(ClientAddress::class, 'client_address', Expr\Join::WITH, 'order_address.id = client_address.id')
            ->andWhere('address.id =:id')
            ->setParameter('id', $id);

        return $qb->getQuery()->getArrayResult(); // Only ArrayResult throw full objecy
    }`

I understand that it was specifically designed in this way, or the ORM operation and the only way to get a full object is through ArrayResult?

**Comment by curry684** [comment] 2017-12-31 11:17
Good to hear it's not a bug!

The behavior you describe is indeed by design - the default QueryProcessor only selects fields that actively participate in the columns. If you need to include specific other fields or full entities you have to provide the query yourself.

This is not documented well yet (on the to-do) but the [unit tests contain a fine example](https://github.com/omines/datatables-bundle/blob/master/tests/Fixtures/AppBundle/DataTable/Type/CustomQueryTableType.php#L42-L54) on how you can separately override both the query and criteria builders.

**Comment by andrzejpakula** [comment] 2017-12-31 12:40
Ok. Very nice. I have yet only one question. It seems that the search engine is not yet implemented ? 
Because when I set searching options to true, and column searchable to true, nothing happens .

**Comment by curry684** [comment] 2017-12-31 15:06
Again, that's a bit of missing docs   😉 

[I extended the documentation to clarify the behavior you are seeing](https://omines.github.io/datatables-bundle/#doctrine-orm).

**Comment by curry684** [comment] 2018-01-05 01:09
Hey @andrzejpakula, are all your issues fixed now?

**Comment by andrzejpakula** [comment] 2018-01-05 08:02
Hi. Yes, thank you for your response. Best regards.

**Comment by curry684** [comment] 2018-01-05 08:33
Let us know if you run into other stuff 👍

**Closed by curry684** 2018-01-05 08:33 UTC
Labels: documentation, question
