### ISSUE TITLE
Default ordering? Doctrine ORM Adapter

### ISSUE THREAD

**Issue by michaelotoole** [omines/datatables-bundle#48] opened 2018-11-08 13:03 UTC
More of a question than an issue based on the default ordering.

I am trying to simply order an entity table based on a `createdAt` field, in descending order. I can do this in the query builder but then the ordering takes precedence on all queries. Adding `order` to the datatables js options only visually sorts it. There is something missing on my server side query that I am just not getting at the moment.

```
->createAdapter(ORMAdapter::class, [
                'entity' => User::class,
                'query' => function (QueryBuilder $qb) {
                    $qb
                    ->select(['u, 'a'])
                    ->from(User::class, 'u')
                    ->leftJoin('u.defaultAddress', 'a')
                    ->orderBy('u.createdAt', 'DESC') // This forces all queries on the callback to use this
                    ;
                }
            ])
```
Probably something really simple but appreciate any guidance.

**Comment by curry684** [comment] 2018-11-08 14:00
As ordering is handled by the adapter based on user input you should configure `orderable` and `orderField` on the column level to get the intended behavior.

As the ORMAdapter only [appends ordering based on UI preferences](https://github.com/omines/datatables-bundle/blob/master/src/Adapter/Doctrine/ORMAdapter.php#L183-L188] instead of replacing them you have the flexibility to use base ordering in your own QueryBuilder, but in your case the `createdAt` dates are likely all unique and therefore make any subsequent ordering criteria pointless.

**Comment by michaelotoole** [comment] 2018-11-08 15:00
My issue is not that of actual ordering, it's more the `default` ordering on whether it is ascending or descending.

The `orderable` definition is just a boolean argument. 

I can add the default sort to the base QueryBuilder; but as you mention, that ordering will then override any UI sorting.

In short, I would like to sort by `createdAt` (or any field I choose) only when there is no other criteria defined? Just not sure how I would go about it without hacking something into my own implementation?

I would like to basically mimic what writing the below for js on a static datatable would provide.
```
 $('#users').initDataTables({{ datatable_settings(datatable) }},
{
 order: [0, 'desc']
})
```

**Comment by curry684** [comment] 2018-11-08 15:24
Ah ok, in that case I think you're looking for [this indeed undocumented feature](https://github.com/omines/datatables-bundle/blob/master/src/DataTable.php#L141-L154).

The following should work:
```
        $table = $this->createDataTable()
            ->add('firstName', TextColumn::class)
            ->add('lastName', TextColumn::class)
            ->addOrderBy('lastName', DataTable::SORT_DESCENDING)
            ->addOrderBy(0, DataTable::SORT_DESCENDING)
```
This contrived example would set the default sorting to lastName then firstName, both descending.

**Comment by michaelotoole** [comment] 2018-11-08 16:07
Spot on, thank you. 

It did seem like something that I was missing, thankfully not blindingly obvious!

Again, thank you for your work on this!

**Comment by curry684** [comment] 2018-11-08 18:30
I'll leave this issue open as a reminder to document it   😉

**Comment by curry684** [comment] 2018-11-19 09:52
Fixed in https://github.com/omines/datatables-bundle/commit/b39d14115a104d1e1972e50ff315fcb3e9211f92

**Closed by curry684** 2018-11-19 09:52 UTC
Labels: documentation, question
