### ISSUE TITLE
Filter column not displayed

### ISSUE THREAD

**Issue by FigaCZ** [omines/datatables-bundle#194] opened 2020-10-13 08:15 UTC
Hello, maybe I didn't search docs deeply, but I am not able to get column filter displayed. I have this setup.

**Controller:**
```
 $userFilter = new ChoiceFilter();
        $userFilter->set([
            'choices' => ['foo' => 'bar', 'bar' => 'baz']
        ]);
        $table = $dataTableFactory->create()
        ->add('created_at', DateTimeColumn::class, ['label' => 'Datum', 'format' => 'j.n.Y H:i', "searchable" => false])
        ->add('userName', TextColumn::class, [
            'label' => 'Uživatel',
            "searchable" => true,
            'render' => function ($value, $context) {
                $user = $context->getUser();

                return $user ? $user->getFirstname().' '.$user->getLastname() : '';
            },
            'filter' => $userFilter
        ])->createAdapter(ORMAdapter::class, [
                'entity' => Copy::class,
            ])
            `->handleRequest($request);
```

**datatables.yaml**

```
# Latest documentation available at https://omines.github.io/datatables-bundle/#configuration
datatables:
    # Set options, as documented at https://datatables.net/reference/option/
    options:
        lengthMenu : [10, 25, 50, 100, 250, 500, 1000, 2500]
        pageLength: 50
        dom: "<'row' <'col-sm-12' ftr>><'row' <'col-sm-6'l><'col-sm-6 text-right'pi>>"
        searching: true

    template_parameters:
        # Example classes to integrate nicely with Bootstrap 3.x
        className: 'table table-striped table-bordered table-hover data-table'
        columnFilter: "both"

    # You can for example override this to "tables" to keep the translation domains separated nicely
    translation_domain: 'messages'
```

I am not able to see column filter. What is wrong? Setup or datatable template. Thanks for reply.

**Comment by mash-potato47** [comment] 2020-11-20 09:43
I'm also experiencing this problem and as mentioned above there is no documentation about how to implement this properly.

Can anyone explain how this should be implemented - is there additional javascript required to get it working?

Thanks!

**Comment by numerogeek** [comment] 2020-11-24 15:45
@FigaCZ have you found any solution ?

**Comment by Gerben321** [comment] 2021-02-01 20:19
Same here.

**Comment by kapcus** [comment] 2021-05-21 21:15
+1

**Comment by GFChris** [comment] 2021-05-24 14:25
+1

**Comment by MadCat34** [comment] 2022-03-10 10:33
Same here...

It could be nice to have documentation for this...

**Comment by ducho** [comment] 2022-04-19 10:01
Hi everybody! Did anyone come up with something with that filter? The author ignores our questions and no documentation.
@MadCat34  @kapcus  @Gerben321 @FigaCZ @mash-potato47

**Comment by RobQuistNL** [comment] 2022-07-22 14:28
nope, filter option doesn't work

**Comment by curry684** [comment] 2022-11-22 22:01
I neither wrote nor use nor reviewed this feature: https://github.com/omines/datatables-bundle/pull/120

Not much I can do to help with an issue I don't really fully understand myself. I'm keeping it open so other people can help each other, that's how open source works.

**Comment by curry684** [comment] 2022-11-22 22:02
There, now it has a label showing I also have no clue about how to solve this issue.

**Comment by RobQuistNL** [comment] 2022-11-23 20:38
> I neither wrote nor use nor reviewed this feature: #120
> 
> Not much I can do to help with an issue I don't really fully understand myself. I'm keeping it open so other people can help each other, that's how open source works.

I didn't mean it personal :) Just read it and it sounds a bit harsh, didn't mean it like that ;) 

I have no clue on how to fix it either, otherwise I would have opened a PR :+)

**Comment by roman-1983** [comment] 2023-04-19 07:35
+1

**Comment by andrea-daru** [comment] 2023-07-03 15:21
Hi all! I'm migrating from [SG Datatable](https://github.com/stwe/DatatablesBundle) to Omines Datatable as the previously mentioned is no longer maintained.
I can't figure out how to configure column filters. I'm experiencing the same problem reported by other user in this issue.
The issue is in closed status because no one can find a solution?
Any info / help will be appreciated.

**Comment by curry684** [comment] 2023-07-03 22:38
Given all the comments above I'd recommend considering this specific feature 'broken'.

We use the library a lot at our company, so we do the maintenance, but only on core features that we developed ourselves and use. It would appear this contributed feature wasn't implemented well unfortunately, nor documented, so we'll likely remove it during an upcoming maintenance round.

**Comment by Shotman** [comment] 2023-07-11 13:27
I managed to have column filtering on a project of mine, for now it's still early (like 30sec ago) later, most likely next week, I'll create a minimal reproduction repo and link it here, no idea if it's the bundle's intend way but if it works it works. 

To sum it up for people who want to try I added this to the initComplete config inside my twig template

```javascript
                initComplete: function () {
                let api = this.api();

                api.columns().every(function () {
                    let column = this;
                    let title = column.header().textContent;
                    let th = column.header();

                    // Create input element
                    let input = document.createElement('input');
                    input.classList.add('form-control');
                    input.addEventListener("click", function(e) {
                        e.stopPropagation();
                    });
                    input.placeholder = title;
                    th.replaceChildren(input);

                    // Event listener for user input
                    let debouncedFunction = debounce(() => {
                        if (column.search() !== this.value) {
                            let idx = [...th.parentNode.children].indexOf(th);
                            let val = input.value;
                            if(val.length < 3) return;
                            api.column(idx + ':visible')
                                .search(val ? '%'+val+'%' : '')
                                .draw();
                        }
                    },500)
                    input.addEventListener('keyup', debouncedFunction);
                });
            }
```

and to my column I added those options : 
``` ["searchable" => true, "filter" => $nameFilter, "operator" => "LIKE"] ```
and $nameFilter is just a TextFilter on wich I called to set method and put "operator" => "LIKE" as well 

And this adds a text input to each column that perfoms a like operation in the backend

**Comment by Chris53897** [comment] 2023-07-28 09:23
@Shotman I assume your solution search for the actual displayed entries (pageLength). Not in the database. Is that correct?
This will be suiteable for small datasets and if all entries are displayed at once.

**Comment by Shotman** [comment] 2023-07-28 09:26
Works on the database, but after some time using that it's not perfect, saving to query parameters doesn't work, url encoding fails because of the added % etc it's a bandaid to have something that kinda works but isn't a real solution but it could be a stepping stone for something solid and stable

**Comment by Chris53897** [comment] 2023-07-28 09:39
Thanks for the fast response. I will wait for the reproducer repo. It that is still the next step.

**Comment by Shotman** [comment] 2023-07-28 10:41
Here is the repo, https://github.com/Shotman/datatable-repo, not the pretiest readme or anything but does the job to recreate what I did on my personal project

**Comment by auroraeosrose** [comment] 2023-12-14 21:27
I have it about 90% working

https://github.com/burroaktoolinc/datatables-bundle/tree/feature_column_searching

That branch has the php/twig side working

Issue is I have to have this in the initComplete in the datatables declaration to get the JS side of the inputs hooked up - might be a better way?  Also this has no debounce which probably should be added.  Any JS gurus have ideas?

```
initComplete: function () {
            let api = this.api();

            api.columns().every(function () {
                const that = this

                // Attach to input fields
                $('input', this.footer()).on('keyup change clear', function () {
                    if (that.search() !== this.value) {
                        that.search(this.value).draw()
                    }
                })

                $('select', this.footer()).on('change', function () {
                    that.search(this.value).draw()
                })
            })
        }
```

**Comment by auroraeosrose** [comment] 2024-02-02 20:17
I have it working now, but it required quite a bit of rework with some features/options copied over from the global search changes made - and it doesn't support multiple filters on a single column (yet)

And the js initComplete is still the way to "hook up" the inputs/selects which is not fabulous

**Comment by Wuffz** [comment] 2024-03-03 09:17
> I have it working now, but it required quite a bit of rework with some features/options copied over from the global search changes made - and it doesn't support multiple filters on a single column (yet)
> 
> And the js initComplete is still the way to "hook up" the inputs/selects which is not fabulous
 Need any help on this? I'd like to see this merged so we can use it haha

**Comment by auroraeosrose** [comment] 2024-03-05 20:23
@Wuffz 

At this point I don't have a lot of impetus to contribute the fix back here - branch is freely available in my fork if you want to try to get it "right" enough to get merged here - https://github.com/burroaktoolinc/datatables-bundle/tree/feature_column_searching

It's working for us off our fork with the caveat of no multiple filters (cause we don't need it)

**Closed** 2024-05-12 22:45 UTC
Labels: help wanted, question, documentation, no-issue-activity
