### ISSUE TITLE
Cannot AutoWire Service ...\Twig\DataTablesExtension...

### ISSUE THREAD

**Issue by mzimhle** [omines/datatables-bundle#122] opened 2020-01-23 11:14 UTC
When I try to run the command:

> composer require omines/datatables-bunde

I get the following error:

>  Cannot autowire service "Omines\DataTablesBundle\Twig\DataTablesExtension": argument "$translator" of method "__construct()" has type "Symfony\Contracts\Translation\TranslatorInterface"
> !!    but this class was not found.

Its a clean installation as in I have the most minimum things in my application, I tried to install "composer require symfony/translation" , that still did not help, please assist.

Regards,

**Comment by curry684** [comment] 2020-02-10 09:54
If it's really minimal you likely missed the contracts. `composer req symfony/contracts` should fix it.

This is also a bug on our end as we should explicitly depend on it. Will fix.

**Comment by curry684** [comment] 2020-02-10 09:59
Uhm no it's not a bug - we depend on `symfony/translation` because of the Twig extension so the contracts must already be there.

What version were you installing?

**Comment by curry684** [comment] 2020-02-24 12:06
Closing this as, given the information provided right now, it's not an issue with the bundle.

**Closed by curry684** 2020-02-24 12:06 UTC
