### ISSUE TITLE
Multi Values Calculation

### ISSUE THREAD

**Issue by xDeSwa** [omines/datatables-bundle#327] opened 2024-01-04 15:44 UTC
hi, 

i created stock manager; i got correct stock number when use dd on controller. (400)

![dd_controller](https://github.com/omines/datatables-bundle/assets/33868586/f5787706-d995-4597-b946-a2ee72a9ca52)

**DB data;**
![phpmyadmin_datas](https://github.com/omines/datatables-bundle/assets/33868586/21cd595a-2f95-4e08-85a0-21e6d9b6d201)

**TwigStringColum;**
![twigstring](https://github.com/omines/datatables-bundle/assets/33868586/fee8f8ba-3e3e-4182-be5e-bbfa9a12b8be)

**TwigStringColum with for loop (its calculated called twice data);**
![Screenshot 2024-01-04 at 18-40-26 Stok Yönetimi _ Yönetim Paneli](https://github.com/omines/datatables-bundle/assets/33868586/1e1492f7-90e9-44b3-bca6-73f1fac6e937)

**Entity / this calculating Collection items in loop**
![getToplamStok](https://github.com/omines/datatables-bundle/assets/33868586/85d625bf-ca11-41f1-9780-b8e97d72aa71)

**Result;**
![tablo](https://github.com/omines/datatables-bundle/assets/33868586/17ef7366-dce0-4b16-8d74-40ae233f3057)

I couldn't figure out what caused this.

**Comment by curry684** [comment] 2024-01-08 08:29
The sum of the items in your 4th image is 800, that's probably the root cause. But apart from that with this information I'm not really seeing an issue in this bundle. Please provide more information pointing to a bundle issue.

**Comment by xDeSwa** [comment] 2024-01-08 08:43
thanks for reply, 
i mean data coming twice. i tried without datatables thats ok (dd, standart table, bootstrap table etc..). 
they calculated 400.

**Comment by curry684** [comment] 2024-01-08 09:00
Again, with this information I see no bundle issue. There is no code in the bundle which actually multiplies values by 2 in a column. Therefore your code must be doing that.

Please do some real debugging, currently there is no indication whatsoever you are experiencing an issue in this bundle. Without solid data backing that up I will close the issue.

**Closed** 2024-03-16 22:45 UTC
Labels: no-issue-activity, insufficient-info
